[tool.poetry]
name = "discord-party-dingomata"
version = "0.1.0"
description = "Distribute game codes on Discord at random to people."
authors = ["SnazzyFox <12706268+snazzyfox@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"  # Required for random.sample with weights
"discord.py" = "^1.7.3"
discord-py-slash-command = "^2.4.2"
pydantic = {extras = ["dotenv"], version = "^1.8.2"}
PyYAML = "^5.4.1"
SQLAlchemy = {extras = ["asyncio"], version = "^1.4.22"}
aiosqlite = "^0.17.0"
pytz = "^2021.1"
python-dateutil = "^2.8.2"
async-cache = "^1.1.1"

[tool.poetry.dev-dependencies]
pyinstaller = "^4.5.1"
mypy = "^0.910"
flake8 = "^3.9.2"
types-PyYAML = "^5.4.6"
types-pytz = "^2021.1.2"
types-python-dateutil = "^0.1.6"
"discord.py-stubs" = "^1.7.3"
sqlalchemy-stubs = "^0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
