common:
  # List of role IDs who can use mod-level commands.
  mod_roles: []

  # List of role IDs where pings in text commands are suppressed.
  no_ping_users: []
game_code:
  # List of role IDs that may join the game and their relative weight of being selected.
  # Each user's chances of being selected is the highest weight they have based on their roles.
  # Roles listed without weight has a default weight of 1. Roles not listed are not allowed to join.
  # To give everyone access, use the null (~) key
  player_roles:
    ~: 1

  # Whether to remember players have been selected in each pool and exclude them from future pools.
  exclude_played: false

bedtime:
  # Alert the same user no more than once every this many minutes
  cooldown: 30

  # Alert the user if they send a message within this many hours of their bedtime
  sleep_hours: 6
gamba:
  # What to call points for this server (should be plural if applicable)
  points_name: points

  # Number of daily gamba points to grant
  daily_points: 1000