servers:
  # Dingo Den
  178042794386915328:
    common:
      mod_roles: &mods [552399444105232384, 492485748071727129]  # Dingo and Moderators
    commands:
      whiskey: on
    game_code:
      exclude_played: true
    gamba:
      points_name: cheddar
    text:
      no_pings: *mods

  # Lycaon
  351122293105229835:
    common:
      mod_roles: [858607225617776650]
    gamba:
      points_name: lycoins
